Creacion de funcion Put dentro del servicio 'privateApiService.js'
alkemyTech/BBVA-React-T1 pull request #1
Opened 2022-05-09 19:52 UTC by agusconde18

Se incorpora la funcion Put al privateApiService para realizar actualizaciones de datos

2022-05-09 20:21 UTC, FlaviaCohen requested changes

2022-05-09 20:21 UTC, FlaviaCohen commented on .gitignore
> +package.json
El package.json no debe ir en el .gitignore ya que si llegaras a instalar una libreria tus compañeros no podrían instalarla.

2022-05-09 20:21 UTC, FlaviaCohen commented on .gitignore
> +.gitignore
El .gitignore tampoco debe ir dentro del .gitignore :P

2022-05-09 20:21 UTC, FlaviaCohen commented on src/Services/privateApiService.js
> +        Group: 1                //Aqui va el ID del equipo!!
Por favor preguntarle a Angeles cual es el ID del equipo, no estoy segura de que sea 1 o 2.

2022-05-09 20:22 UTC, FlaviaCohen requested changes

2022-05-09 20:22 UTC, FlaviaCohen commented on src/Services/privateApiService.js
> +export default Get
En vez de exportarlo como default pone un `export` en la linea 27 antes del `const Put` ya que tus compañeros también van a exportar servicios desde este mismo archivo.

2022-05-09 20:28 UTC, FlaviaCohen commented
Te cambie el nombre del PR, recordá que siempre debe llamarse como el id de la tarjeta y una breve descripcion

2022-05-10 14:28 UTC, agusconde18 commented on .gitignore
> +package.json
Resuelto

2022-05-10 14:28 UTC, agusconde18 commented on .gitignore
> +.gitignore
Resuelto

2022-05-10 14:28 UTC, agusconde18 commented on src/Services/privateApiService.js
> +        Group: 1                //Aqui va el ID del equipo!!
Queda a la espera de la respuesta de angeles y luego hago un commit

2022-05-10 15:47 UTC, agusconde18 commented on src/Services/privateApiService.js
> +        Group: 1                //Aqui va el ID del equipo!!
Resuelto

2022-05-10 16:26 UTC, FlaviaCohen approved these changes

2022-05-10 16:26 UTC, merged