Feature/fs01-27 método privado Post
alkemyTech/BBVA-React-T1 pull request #12
Opened 2022-05-11 12:44 UTC by martinapereyra

Creo que método para hacer peticiones POST a los endpoints privados de la API

2022-05-11 13:28 UTC, FlaviaCohen requested changes

2022-05-11 13:28 UTC, FlaviaCohen commented on src/Services/privateApiService.js
> +    .then(res => {return res})
Cuando la funcion no tiene logica extra y solo es un return las arrow functions tienen return implicito. Por eso lo declaramos asi: 

`.then(res =>res)`

2022-05-11 13:28 UTC, FlaviaCohen commented on src/Services/privateApiService.js
> +    .catch(err => console.log(err))
Nunca dejamos console.logs en los PRs. Tendrias que retornar el error

2022-05-11 15:21 UTC, martinapereyra commented
👍

2022-05-12 01:19 UTC, FlaviaCohen approved these changes

2022-05-12 01:19 UTC, merged