Feature/fs01-33 | Login form
alkemyTech/BBVA-React-T1 pull request #18
Opened 2022-05-12 15:14 UTC by jenkobud

Adjunto videos del Login form

Responsiveness:
https://user-images.githubusercontent.com/43655683/168108734-7aee67d3-1dc4-48c4-ba32-344219c3b8d6.mp4

Chequeo de validaciones:
https://user-images.githubusercontent.com/43655683/168108850-2f8d7b32-2515-40a3-839f-dac76bd72544.mp4

2022-05-12 22:48 UTC, FlaviaCohen requested changes

2022-05-12 22:48 UTC, FlaviaCohen commented on src/Components/Login/LoginForm.css
> +.login-container div{
Asignale una clase al div que quieras estilar ya que referirse al elemento por su rol es una mala practica y lleva a colision de estilos

2022-05-12 22:48 UTC, FlaviaCohen commented on src/Components/Login/LoginForm.css
> +.form-container button {
Mismo comentario

2022-05-12 22:48 UTC, FlaviaCohen commented on src/Components/Login/LoginForm.css
> +.form-container button:hover {
Mismo comentario

2022-05-12 22:48 UTC, FlaviaCohen commented on src/Components/Login/LoginForm.css
> +.form-container form{
Mismo comentario y para todos los elementos que no tengan clase

2022-05-12 22:48 UTC, FlaviaCohen commented on src/Components/Login/LoginForm.css
> +.inputer{ margin: 10px 0 !important;}
Nunca usamos important, es una muy mala practica. Si no te esta tomando el estilo es porque algo esta colisionando. Utiliza el inspector del browser para ver que es.

2022-05-12 22:48 UTC, FlaviaCohen commented on src/Components/Login/LoginForm.js
> +  if(password.length < minPasswordLength) return 'Contraseña muy corta';
Esto es un error en la tarjeta. No deberia haber validacion de contraseña en el formulario de login mas que la que devuelve la api verificando que sea la contraseña correcta.

2022-05-13 12:41 UTC, jenkobud commented
Cambios realizados! 👍

2022-05-13 14:28 UTC, FlaviaCohen requested changes

2022-05-13 14:28 UTC, FlaviaCohen commented on src/Components/Login/LoginForm.js
> +    } catch (err) { /* Caso en que la petición devuelve error */ }
Si la peticion devuelve error tendrias que mostrar ese error. Por lo general el error viene con un mensaje, podrias mostrar en rojo ese mensaje

2022-05-13 14:28 UTC, FlaviaCohen commented
Solucionar conflictos

2022-05-13 15:05 UTC, jenkobud commented
Conflictos resueltos 👍

2022-05-14 13:58 UTC, FlaviaCohen requested changes

2022-05-14 13:58 UTC, FlaviaCohen commented on src/Components/Login/LoginForm.css
> +  .img-container img{display: none;}
Hay que darle un nombre a este elemento img. img-container es un nombre muy comun y seguramente alguien mas lo utilice, si haces referencia a la imagen por su rol es probable que lleve a colision de estilos.

2022-05-14 13:58 UTC, FlaviaCohen commented on src/Components/Login/LoginForm.js
> +    } catch (err) { /* Caso en que la petición devuelve error */ }
Falta resolver esto

2022-05-14 13:59 UTC, FlaviaCohen commented
Solucionar conflictos

2022-05-16 13:14 UTC, jenkobud commented
Confilctos solucionados! 👍 

Adjunto vista:
![image](https://user-images.githubusercontent.com/43655683/168600735-b3835bb2-83c0-45b3-878a-1ac975c95bde.png)

2022-05-16 14:48 UTC, FlaviaCohen requested changes

2022-05-16 14:48 UTC, FlaviaCohen commented on src/Components/Auth/LoginForm.js
> +    if('error' in data) {
Que quisiste hacer con este condicional?

2022-05-16 14:48 UTC, FlaviaCohen commented on src/Components/Auth/LoginForm.js
> +    e.preventDefault();
La idea de esta funcion seria que hagas el post con la data del formulario, en caso de que res.data te devuelva que esta todo bien haces el localStorage.setItem con el token que te devuelve res.data, sino mostras un en pantalla el error que corresponda. No tiene sentido separar la funcion loginVerification. Tenes que hacerlo todo acá. 

De hecho tendrias que hacer un redirect a home una vez que seteaste el token en localStorage

2022-05-16 14:49 UTC, FlaviaCohen commented
Solucionar conflictos

2022-05-18 04:07 UTC, jenkobud commented
Cambios realizados :+1:

2022-05-18 13:54 UTC, FlaviaCohen requested changes

2022-05-18 13:54 UTC, FlaviaCohen commented on src/Components/Auth/LoginForm.js
> +      console.log(data.data.token);
aca quedo un console.log

2022-05-18 13:54 UTC, FlaviaCohen commented on src/Components/Auth/LoginForm.js
> +        return;
este return podrias ponerlo en la linea 53 antes del setAlertState

2022-05-18 19:01 UTC, FlaviaCohen approved these changes

2022-05-18 19:01 UTC, merged