feature/FS01-31 | Post function for public API
alkemyTech/BBVA-React-T1 pull request #2
Opened 2022-05-09 21:51 UTC by jenkobud

Creación de método Post reutilizable para endpoint de API pública.

2022-05-09 22:18 UTC, FlaviaCohen requested changes

2022-05-09 22:18 UTC, FlaviaCohen commented on src/Services/publicApiService.js
> +    let postUrl = `${API_BASE_URL}/${route}}`;
Si no vas a utilizar esta variable en dos lugares no es necesario que la declares, directamente pasale `${API_BASE_URL}/${route}}` como primer parámetro del axios.post

2022-05-10 12:29 UTC, jenkobud commented on src/Services/publicApiService.js
> +    let postUrl = `${API_BASE_URL}/${route}}`;
👍 gracias por el feedback! Ya cambiado

2022-05-10 13:14 UTC, FlaviaCohen requested changes

2022-05-10 13:14 UTC, FlaviaCohen commented on src/Services/publicApiService.js
>      .then(res => console.log(res))
Faltaria que en vez de un console.log retorne res, ya que vamos a necesitar obtener esa respuesta cuando utilicemos este servicio.

2022-05-10 14:32 UTC, jenkobud commented on src/Services/publicApiService.js
>      .then(res => console.log(res))
Una consulta, tengo que devolver _si o si_ la res, o podría devolver la promesa (en este caso axios.post) especificando el tipo de respuesta de la función?

2022-05-10 19:03 UTC, jenkobud commented
Cambios del return realizados! :)

2022-05-11 02:19 UTC, FlaviaCohen commented on src/Services/publicApiService.js
>      .then(res => console.log(res))
Yo devolveria res porque tambien pondria un caso .catch en el que devuelvo el error en caso de que lo hubiera.

2022-05-11 02:21 UTC, FlaviaCohen requested changes

2022-05-11 02:21 UTC, FlaviaCohen commented on src/Services/publicApiService.js
> +    return(axios.post(`${API_BASE_URL}${route}`, bodyObj, config.headers));
perdon jenko hoy me preguntaste y fue medio vaga mi respuesta. 
Seria correcto que devuelvas res y error, por ende tendrias que ponerle otra sintaxis a esto, sea try catch o then y catch pero la idea es que devuelvan tanto respuesta exitosa como error.

2022-05-11 13:00 UTC, jenkobud commented
👍  Cambios realizados!

2022-05-11 13:31 UTC, FlaviaCohen commented
Resolver conflictos

2022-05-11 13:41 UTC, jenkobud commented
Conflictos solucionados! 👍

2022-05-11 13:51 UTC, FlaviaCohen approved these changes

2022-05-11 13:51 UTC, merged