Feature/fs01 102 | Header para backoffice + sidebar
alkemyTech/BBVA-React-T1 pull request #23
Opened 2022-05-13 08:46 UTC by NahuelAlfano

Se crea una carpeta ( BackofficeHeader ) que contiene 2 componentes:
- BackofficeHeader.js que contiene el navbar con boton para mostrar el sidebar.
- Sidebar.js que exporta la data a mostrar en el sidebar del header.

Se agrego la ruta al backoffice header y se comento en app.js

Se utilizo 'react-icons' para el men

https://user-images.githubusercontent.com/53476402/168246497-10488502-932f-4979-9e61-21c658a21a17.mp4

2022-05-13 13:39 UTC, FlaviaCohen commented
Esta muy bueno... se esta mostrando en la ruta publica aparentemente. Por eso se ven los dos headers. Deberia mostrarse solo en las rutas que empiecen con backoffice.

2022-05-13 13:45 UTC, FlaviaCohen requested changes

2022-05-16 11:32 UTC, NahuelAlfano commented
@FlaviaCohen se solucionaron conflictos, se arreglaron los comentarios que me dejaste. También se modifico la funcion get en public services porque no devolvía nada ( le avise a la persona que lo hizo para que lo revise por si quería, la modifique y deje comentado lo que no me funcionaba ). Se corrigio la ruta de /contacto y se le agrego el componente que correspondía

2022-05-16 14:18 UTC, FlaviaCohen requested changes

2022-05-16 14:18 UTC, FlaviaCohen commented on src/Components/BackofficeHeader/BackofficeHeader.js
> +        const res = Get('/organization', 1)
Esto debe ir en una funcion por fuera del useEffect y dentro solo ejecutarla. Podes llamarla getOrgData

2022-05-16 14:18 UTC, FlaviaCohen commented on src/Services/publicApiService.js
> +    return res;
Esta concatenacion no debe hacerce aca, debe hacerse en el componente. Este servicio solo recibira route, ni siquiera id. Desde el componente vos vas a armar la url completa a la que necesites que apunte este servicio get

2022-05-16 14:20 UTC, FlaviaCohen commented on src/Components/BackofficeHeader/BackofficeHeader.js
> +        axios.get('https://ongapi.alkemy.org/api/organization/1')
No esta resuelto del todo, te deje otro comentario

2022-05-16 14:21 UTC, FlaviaCohen commented on src/Components/BackofficeHeader/BackofficeHeader.js
> +        const res = Get('/organization', 1)
Ademas fijate que te deje comentario sobre el servicio get, no debe contactenar url sino que la concatenacion tenes que hacerla vos en el componente que lo uses. Por eso no le vas a mandar solo '/organization' sino la url completa, incluyendo el id

2022-05-16 14:27 UTC, NahuelAlfano commented on src/Components/BackofficeHeader/BackofficeHeader.js
> +        const res = Get('/organization', 1)
genial, ya hable con erika para modificar el get en el servicio. Cuando se haga ese solucione esa parte corrijo aca y aviso.

2022-05-16 17:24 UTC, NahuelAlfano commented on src/Services/publicApiService.js
> +    return res;
ya se corrigió en la publicApiServices y en el backoffice header

2022-05-16 17:25 UTC, NahuelAlfano commented
@FlaviaCohen creo que ya esta. falta la implementación del layout privado que lo hago después en otra branch nueva.

2022-05-16 22:32 UTC, FlaviaCohen commented
> @FlaviaCohen creo que ya esta. falta la implementación del layout privado que lo hago después en otra branch nueva.

Perfecto porque ahi vi que corresponde a otra tarea el layout

2022-05-16 22:36 UTC, FlaviaCohen approved these changes

2022-05-16 22:36 UTC, FlaviaCohen commented on src/Components/BackofficeHeader/BackofficeHeader.js
> +        const res = await Get(process.env.REACT_APP_URL_BASE_ENDPOINT + process.env.REACT_APP_URL_ORGANIZATION_PATH + '/' + 1)
Creo que no es necesario mandarle un id, con que el endpoint sea /organization te devuelve la informacion. 
No entiendo muy bien la diferencia en el swagger pero parecen traer la misma data.

2022-05-16 22:36 UTC, merged