Feature/FS01-62/Users List
alkemyTech/BBVA-React-T1 pull request #24
Opened 2022-05-13 09:58 UTC by mattverach

https://user-images.githubusercontent.com/85206468/168248040-a060c627-d904-4820-a810-aa0d023a1954.mp4

2022-05-13 13:57 UTC, FlaviaCohen commented
Por lo que veo en el video falta que el formulario este lleno de la informacion del usuario cuando recibe id, pero eso no es parte de tu tarea.

2022-05-13 14:00 UTC, FlaviaCohen requested changes

2022-05-13 15:02 UTC, mattverach commented
Si, me pareció raro también pero me fije y UserForm esta desde el initial commit

2022-05-14 13:33 UTC, FlaviaCohen approved these changes

2022-05-14 13:34 UTC, merged