Feature/fs01 37
alkemyTech/BBVA-React-T1 pull request #32
Opened 2022-05-13 21:58 UTC by agusconde18

![imagen](https://user-images.githubusercontent.com/70043267/168394626-b103da75-9105-4b15-beb4-c259dcefc416.png)
La imagen de arriba corresponde a actualizacion

![imagen](https://user-images.githubusercontent.com/70043267/168394688-747d528f-2fe3-49c6-85b5-cff62fd05823.png)
La superior corresponde a creacion

Unicamente se muestran los N° de orden disponibles y algunos extra para que tenga flexibilidad de seleciconar

2022-05-14 13:56 UTC, FlaviaCohen requested changes

2022-05-14 13:56 UTC, FlaviaCohen commented on src/Components/Slides/SlidesForm.js
> +    const snackErrorCargaDatos = () =>{
No mezclemos idiomas

2022-05-14 13:56 UTC, FlaviaCohen commented on src/Components/Slides/SlidesForm.js
> +    const actualizacionDeDatos = id !== "create";
No mezclemos idiomas. La idea es que el codigo este siempre declarado en ingles ya que javascript se escribe en inglés. Si se te complica lo dejamos asi pero sabé que no es una buena práctica

2022-05-14 13:56 UTC, FlaviaCohen commented on src/Components/Slides/SlidesForm.js
> +            .then( res => {
Este Get deberia ejecutarse solo si el id existe, porque si no existe estarias en el formulario de creacion y no hay ningun Get que ejecutar

2022-05-14 13:56 UTC, FlaviaCohen commented on src/Components/Slides/SlidesForm.js
>          e.preventDefault();
Esto deberias declararlo en una funcion handleSubmit por fuera del jsx y aca solo ejecutarla. No es una buena practica poner logica compleja en el jsx

2022-05-14 13:56 UTC, FlaviaCohen commented on src/Components/Slides/SlidesForm.js
> +        PrivatePost(process.env.REACT_APP_URL_BASE_ENDPOINT+process.env.REACT_APP_URL_SLIDES_PATH,objectSend);
Aca falta un condicional. No se van a ejecutar ambos servicios. Se va a ejecutar Put solo si el id existe, sino será un Post, pero nunca los dos

2022-05-14 13:56 UTC, FlaviaCohen commented on src/Services/privateApiService.js
> +  return axios.get(`${endpoint}`, config);
los backtips, signo $ y llaves no son necesarios. Hay que pasarle solo endpoint

2022-05-14 13:56 UTC, FlaviaCohen commented on src/Services/privateApiService.js
> +    .post(`${endpoint}`, body, config)
Mismo comentario

2022-05-14 13:56 UTC, FlaviaCohen commented on src/Services/privateApiService.js
> +    return await axios.put(`${route}`,body,config)
Mismo comentario

2022-05-14 14:31 UTC, agusconde18 commented on src/Components/Slides/SlidesForm.js
> +        PrivatePost(process.env.REACT_APP_URL_BASE_ENDPOINT+process.env.REACT_APP_URL_SLIDES_PATH,objectSend);
el condicional esta segun entiendo, solo que lo parti en varias lineas
var promise = (condicion)? put : post ;

2022-05-14 14:33 UTC, agusconde18 commented on src/Components/Slides/SlidesForm.js
>          e.preventDefault();
Esto lo que hace es mostrar unicamente los radio buttons que se pueden elegir, por ejemplo si hay ya un slide con ID 1 no me muestra el radio button 1, es decir que no seria una comprobacion de submit, seria mas una forma de mostrar que esta disponible, ¿se puede dejar o lo saco?

2022-05-14 14:34 UTC, agusconde18 commented on src/Components/Slides/SlidesForm.js
> +            .then( res => {
lo ejecuto para ver que numeros de order estan usados y no mostrarlos al usuario (comentario de abajo), de no ser correcto lo modifico

2022-05-15 19:11 UTC, FlaviaCohen commented on src/Components/Slides/SlidesForm.js
>          e.preventDefault();
No...hay que sacarlo de todas formas. Ponele si queres otro nombre a la funcion, no tiene que ser handleSubmit ya que no seria un submit. Pero no es una buena practica poner logica compleja en el jsx. Se trata de dejar lo mas limpio posible

2022-05-15 19:12 UTC, FlaviaCohen commented on src/Components/Slides/SlidesForm.js
> +        PrivatePost(process.env.REACT_APP_URL_BASE_ENDPOINT+process.env.REACT_APP_URL_SLIDES_PATH,objectSend);
Pero porque la condicion es actualizacionDeDatos y no id? Si lo estas usando solo para comprobar si existe el id, usa id directamente

2022-05-15 19:14 UTC, FlaviaCohen requested changes

2022-05-15 19:14 UTC, FlaviaCohen commented on src/Components/Slides/SlidesForm.js
> +    const dataUpdate= id !== "create";
Esto es lo que digo. Estas creando una variable para hacer una comprobacion que podes hacer directamente con el id.

2022-05-16 11:09 UTC, agusconde18 commented on src/Components/Slides/SlidesForm.js
> +    const dataUpdate= id !== "create";
Solucionado

2022-05-16 11:09 UTC, agusconde18 commented on src/Components/Slides/SlidesForm.js
> +        PrivatePost(process.env.REACT_APP_URL_BASE_ENDPOINT+process.env.REACT_APP_URL_SLIDES_PATH,objectSend);
Solucionado

2022-05-16 11:09 UTC, agusconde18 commented on src/Components/Slides/SlidesForm.js
>          e.preventDefault();
espectacular! gracias por la correccion, corregido

2022-05-16 14:26 UTC, FlaviaCohen approved these changes

2022-05-16 14:26 UTC, FlaviaCohen commented on src/Components/Slides/SlidesForm.js
>                  if(success===true){
El `=== true` no es necesario (perdon, recien lo veo). Con que tu condicional diga `if(success)` alcanza para que compruebe si es true.

2022-05-16 14:28 UTC, FlaviaCohen requested changes

2022-05-16 14:41 UTC, FlaviaCohen approved these changes

2022-05-16 14:41 UTC, FlaviaCohen commented
Solucionar conflictos!

2022-05-16 14:54 UTC, agusconde18 commented
Listo para mergear

2022-05-16 16:06 UTC, FlaviaCohen requested changes

2022-05-16 16:06 UTC, FlaviaCohen commented on src/App.js
> +
Ojo que aca en el pull que hiciste borraste una ruta

2022-05-16 16:06 UTC, FlaviaCohen commented on src/Services/privateApiService.js
> +
aca borraste el then y catch de esta funcion

2022-05-16 16:35 UTC, agusconde18 commented on src/Services/privateApiService.js
> +
solucionado

2022-05-16 22:38 UTC, FlaviaCohen approved these changes

2022-05-16 22:38 UTC, merged