Feature/fs01 105
alkemyTech/BBVA-React-T1 pull request #33
Opened 2022-05-13 23:46 UTC by agusconde18

https://user-images.githubusercontent.com/70043267/168402000-e0582c74-cfd6-43c2-ba47-e9108a37dada.mp4

Se crea sidebar para posteriormente implementarlo en header de backoffice cuando un compañero lo genere.

La ruta /side unicamente se creo para la prueba y ya se borro

2022-05-14 13:21 UTC, FlaviaCohen requested changes

2022-05-14 13:21 UTC, FlaviaCohen commented on src/Components/Backoffice/ListadoRutas/ListadoRutas.js
> +import './ListadoRutas.css'
La idea de no mezclar idiomas aplica tambien para los nombres de los archivos, de todas formas lo voy a mergear asi para no demorarte pero sabé que sería mejor que esté en inglés

2022-05-14 13:21 UTC, FlaviaCohen commented on src/Components/Backoffice/Sidebar/Sidebar.js
> +    const toggleDrawer = ( open) => (event) => {
Probaste haciendo un toggle mas simple?

Seria algo así: 

```
const [isOpen, setIsOpen] = useState(false);

const toggleDrawer = () => {
    setIsOpen(!isOpen)
}
```
La función se la pasas al onClick del icono. 
Es una forma muy común declarar funciones toggle

2022-05-14 14:01 UTC, FlaviaCohen requested changes

2022-05-14 14:01 UTC, FlaviaCohen commented on src/App.js
>              <Route path="/backoffice/create-testimonials" component={TestimonialForm} />
Aca hay un conflicto sin resolver!

2022-05-15 18:56 UTC, FlaviaCohen requested changes

2022-05-15 18:56 UTC, FlaviaCohen commented on src/Components/Backoffice/RoutesLIst/RoutesList.js
> +const ListadoRutas = () => {
Misma correccion. Tratemos de poner los nombres en ingles

2022-05-15 18:56 UTC, FlaviaCohen commented on src/Components/Backoffice/Sidebar/Sidebar.js
> +            onClose={setIsOpen( false)}
Ya no hace falta que le pases estas funciones. Con un onClick={toggleDrawer} estaria bien. De hecho tenes declarada esa funcion y no la estas usando en ningun lado.

2022-05-16 11:30 UTC, agusconde18 commented on src/Components/Backoffice/RoutesLIst/RoutesList.js
> +const ListadoRutas = () => {
Solucionado

2022-05-16 11:30 UTC, agusconde18 commented on src/Components/Backoffice/Sidebar/Sidebar.js
> +            onClose={setIsOpen( false)}
Espectacular solucionado

2022-05-16 14:51 UTC, FlaviaCohen approved these changes

2022-05-16 16:15 UTC, FlaviaCohen approved these changes

2022-05-16 16:15 UTC, merged