FS01-51/Feature/Incorporacion componente Nosotros
alkemyTech/BBVA-React-T1 pull request #4
Opened 2022-05-10 15:43 UTC by agusconde18

Se procede a incorporar el ruteo y componente nosotros.
Se entiende que el header se incorporara de forma global y tambien se entiende que otra persona esta encargada de agregar la carga dinamica de los datos de dicho componente.

Adicionalmente a lo pedido se elimino el contenido que viene por default al crear el proyecto de react del archivo App.js

2022-05-10 15:43 UTC, agusconde18 commented
![imagen](https://user-images.githubusercontent.com/70043267/167668687-990b4129-8ba7-477c-8dc5-c6e1eb65551f.png)

2022-05-11 02:10 UTC, FlaviaCohen requested changes

2022-05-11 02:10 UTC, FlaviaCohen commented on src/Components/About/Nosotros.js
> +       text : "Sobre Nosotros"
Ya que el texto va a ser un string seria mejor inicializarlo como un string vacio, no es necesario que sea un objecto.

2022-05-11 02:39 UTC, FlaviaCohen commented
Faltaria renderizar el texto traido desde la Api. Cualquier cosa consultale a Julia del team 2 que ella lo pudo hacer.

2022-05-12 15:32 UTC, agusconde18 commented on src/Components/About/Nosotros.js
> +       text : "Sobre Nosotros"
resuelto

2022-05-12 15:34 UTC, agusconde18 commented
![imagen](https://user-images.githubusercontent.com/70043267/168113064-4de69a3a-e6b4-4b55-bbb6-15c11761cf7e.png)
Comparto imagen de como quedo, el listado inferior lo agerga un compañero luego que este mergeado

2022-05-12 15:37 UTC, agusconde18 commented
https://user-images.githubusercontent.com/70043267/168114030-2f0dd698-a733-470b-ad45-0b36e2837159.mp4
Subo video para ver la carga del spinner

2022-05-12 22:16 UTC, FlaviaCohen commented
Solucionar conflictos

2022-05-12 22:22 UTC, FlaviaCohen requested changes

2022-05-12 22:22 UTC, FlaviaCohen commented on src/Components/About/Nosotros.css
> +p {
Este elemento debe tener una clase sino va a generar colision de estilos en otros componentes.

2022-05-12 22:22 UTC, FlaviaCohen commented on src/Components/About/Nosotros.js
> +import '../../App.css'
Porque estas importando el estilo de App acá? Se supone que el estilo de App esta disponible para todos los componentes que se rendericen dentro de App si necesidad de importarlo

2022-05-12 22:22 UTC, FlaviaCohen commented on src/Components/About/Nosotros.js
> +        Get("organization").then( res => {
Esta logica deberia estar dentro de una funcion por fuera de useEffect, y dentro solo ejecutada

2022-05-12 22:22 UTC, FlaviaCohen commented on src/Components/Spinner/Spinner.css
> +    background: rgb(228,226,226);
Creo que la linea 7 no es necesaria ya que tenes dos veces definido background

2022-05-12 22:22 UTC, FlaviaCohen commented on src/Services/publicApiService.js
> +    .get(`https://ongapi.alkemy.org/api/${route}${id}`, config)
Se que no corresponde a esta tarea pero hay que reemplazar esta url por la variable de ambiente correspondiente.

2022-05-12 22:23 UTC, FlaviaCohen commented
Solucionar conflictos

2022-05-12 22:57 UTC, agusconde18 commented on src/Services/publicApiService.js
> +    .get(`https://ongapi.alkemy.org/api/${route}${id}`, config)
solucionado en merge

2022-05-12 23:03 UTC, agusconde18 commented on src/Components/Spinner/Spinner.css
> +    background: rgb(228,226,226);
solucionado

2022-05-12 23:04 UTC, agusconde18 commented on src/Components/About/Nosotros.js
> +        Get("organization").then( res => {
Solucionado

2022-05-12 23:04 UTC, agusconde18 commented on src/Components/About/Nosotros.js
> +import '../../App.css'
Ok! eliminado, desconocia eso

2022-05-12 23:04 UTC, agusconde18 commented on src/Components/About/Nosotros.css
> +p {
Quedo de un test, se elimino y se paso a una clase correspondiente (linea 27)

2022-05-12 23:07 UTC, FlaviaCohen requested changes

2022-05-12 23:07 UTC, FlaviaCohen commented on src/Components/About/Nosotros.js
> +        Get("organization").then( res => {
Re hincha, pero el metodo deberia llamarse getOrganizationData para que el nombre sea mas representativo. getDataFromAPI puede ser cualquier get

2022-05-12 23:38 UTC, agusconde18 commented on src/Components/About/Nosotros.js
> +        Get("organization").then( res => {
No hay drama, super logico, cambiado

2022-05-12 23:55 UTC, FlaviaCohen approved these changes

2022-05-12 23:55 UTC, merged