Feature/fs01 38 - Creación/Edición de testimonios
alkemyTech/BBVA-React-T1 pull request #47
Opened 2022-05-17 15:22 UTC by martinapereyra

Creo formulario de creación/edición de testimonios

2022-05-17 15:53 UTC, FlaviaCohen requested changes

2022-05-17 15:53 UTC, FlaviaCohen commented on src/Components/Testimonials/TestimonialsForm.js
> +    return formCorrecto
Tratemos de no mezclar idiomas

2022-05-17 15:59 UTC, martinapereyra commented on src/Components/Testimonials/TestimonialsForm.js
> +    return formCorrecto
Cambiado!

2022-05-18 03:11 UTC, FlaviaCohen approved these changes

2022-05-18 03:12 UTC, merged