Feature/FS01-116/Proteccion de rutas
alkemyTech/BBVA-React-T1 pull request #49
Opened 2022-05-17 17:39 UTC by agusconde18

https://user-images.githubusercontent.com/70043267/168876073-bab8977e-0eeb-4a0f-a2c6-a548e9137a94.mp4

2022-05-18 03:27 UTC, FlaviaCohen requested changes

2022-05-18 03:27 UTC, FlaviaCohen commented on src/Services/privateApiService.js
> +  return getToken() && getToken().length>5
porque el .length>5?
Podrias hacer la comprobacion directamente con getToken

2022-05-18 03:27 UTC, FlaviaCohen commented on src/Components/Utils/Auth/Auth.js
> +export const LogInTestOrReddirect = () => {
No veo muy necesario hacer este componente.

2022-05-18 03:29 UTC, FlaviaCohen commented
En vez de repetir ese componente test de login en cada vista podrias hacer en app una comprobacion con el token. 

`{getToken() && ...todas las rutas que requieran autenticacion}`

2022-05-18 03:29 UTC, FlaviaCohen commented
Solucionar conflictos

2022-05-18 19:22 UTC, agusconde18 commented on src/Components/Utils/Auth/Auth.js
> +export const LogInTestOrReddirect = () => {
OK solucionado

2022-05-18 19:22 UTC, agusconde18 commented on src/Services/privateApiService.js
> +  return getToken() && getToken().length>5
Ok, solucionado

2022-05-19 00:15 UTC, FlaviaCohen commented on src/Services/privateApiService.js
> +  return getToken()
Si lo unico que esta haciendo esta funcion es ejecutar getToken te parece que es necesario que exista? Podrias usar directamente getToken.

2022-05-19 00:45 UTC, merged