Feature/fs01-77/Loading and snackbar error
alkemyTech/BBVA-React-T1 pull request #50
Opened 2022-05-17 17:59 UTC by agusconde18

https://user-images.githubusercontent.com/70043267/168879393-cbcebbf5-8b63-49e0-8356-e5266fa8819a.mp4

https://user-images.githubusercontent.com/70043267/168879533-f24362cb-767f-480f-982c-018cf7933d9e.mp4

2022-05-17 18:01 UTC, agusconde18 commented
Para completar la tarea falta la lanfing page (Home, pero estoy bloqueado a la espera de que nahuel complete la tarea) pero subo por si hay correcciones ya tenerlas y cuando implemente en la landing

2022-05-18 03:19 UTC, FlaviaCohen requested changes

2022-05-18 03:19 UTC, FlaviaCohen commented on src/Components/About/Nosotros.js
>              const data=res.data.data;
aca estas declarando este const data pero no lo estas usando

2022-05-18 03:19 UTC, FlaviaCohen commented on src/Components/About/Nosotros.js
>          loaded:false
sobreNosotros y SetSobreNosotros tendria que ser `AboutData y setAboutData` o `text y setText`, no hay que mezclar idiomas

2022-05-18 03:19 UTC, FlaviaCohen commented on src/Components/About/Nosotros.js
> +    const [snack, setSnack] = useState({
Los estados hay que ordenarlos todos juntos al principio del componente

2022-05-18 19:24 UTC, agusconde18 commented on src/Components/About/Nosotros.js
>              const data=res.data.data;
ok

2022-05-18 19:26 UTC, agusconde18 commented on src/Components/About/Nosotros.js
>          loaded:false
ok

2022-05-18 19:26 UTC, agusconde18 commented on src/Components/About/Nosotros.js
> +    const [snack, setSnack] = useState({
Desconocia eso, gracias por el comentario!! c:

2022-05-18 19:31 UTC, agusconde18 commented
Todo solucionado, si llega a existir un comentario mas me es muy util, sino ya nahuel me comento que esta proximo a terminar y luego lo implemento todo esto en la home

2022-05-19 16:03 UTC, FlaviaCohen requested changes

2022-05-19 16:03 UTC, FlaviaCohen commented on src/Components/About/Nosotros.js
> +    const {appData, setAppData} = GetAppContext();
Me parece que esto te quedo de otra branch

2022-05-19 16:03 UTC, FlaviaCohen commented on src/Components/Activities/ActivitiesForm.js
> +    const {appData, setAppData} = GetAppContext();
Lo mismo...se te mezclaron las branch agus.

2022-05-19 16:05 UTC, agusconde18 commented on src/Components/Activities/ActivitiesForm.js
> +    const {appData, setAppData} = GetAppContext();
hasta donde yo se no se mezclaron, lo q paso es que implemente el spinenr y snack con context de manera global

2022-05-19 17:39 UTC, FlaviaCohen approved these changes

2022-05-19 17:39 UTC, merged