Feature/fs01 59 - Listado Actividades Backoffice
alkemyTech/BBVA-React-T1 pull request #51
Opened 2022-05-17 20:04 UTC by martinapereyra

Creo listado de actividades para backoffice
![image](https://user-images.githubusercontent.com/84364767/168900304-f02f753e-e0c7-4173-82f8-98510c0c2dea.png)

2022-05-18 03:33 UTC, FlaviaCohen approved these changes

2022-05-18 03:33 UTC, FlaviaCohen commented
Solucionar conflictos

2022-05-18 04:09 UTC, martinapereyra commented
Listo!

2022-05-18 13:51 UTC, FlaviaCohen commented
Sigue habiendo porque mergee el layout de backoffice y seguro eso generó nuevos conflictos

2022-05-18 20:35 UTC, martinapereyra commented
Soluciono problemas de merge y agrego función para eliminar

2022-05-19 00:18 UTC, FlaviaCohen requested changes

2022-05-19 00:19 UTC, FlaviaCohen commented
Solucionar conflictos

2022-05-19 01:04 UTC, martinapereyra commented on src/Components/Activities/ActivitiesList.js
> +  const deleteActivitie = async (id) => {
si, no sé que me pasó. Solucionado!

2022-05-19 01:04 UTC, martinapereyra commented
Listo!

2022-05-19 02:16 UTC, martinapereyra commented
👍👍

2022-05-19 14:23 UTC, FlaviaCohen approved these changes

2022-05-19 14:23 UTC, merged