FS01-68
alkemyTech/BBVA-React-T1 pull request #6
Opened 2022-05-10 18:37 UTC by agusconde18

Se crea el archivo .env y se pushea para el almacen de el endpoint de la BASE_URL y el path de Miembros

2022-05-11 02:04 UTC, FlaviaCohen commented
Solucionar conflictos

2022-05-11 02:06 UTC, FlaviaCohen requested changes

2022-05-11 02:06 UTC, FlaviaCohen commented on .gitignore
> +#.env
Podes borrarlo directamente en vez de comentarlo.

2022-05-11 02:06 UTC, FlaviaCohen commented on src/Services/privateApiService.js
>  const Get = () => {
Este metodo Get podriamos borrarlo directamente ya que es parte del template

2022-05-11 02:06 UTC, FlaviaCohen commented on src/Services/privateApiService.js
>  export default Get
Y este export default tambien

2022-05-11 15:02 UTC, agusconde18 commented on .gitignore
> +#.env
Solucionado

2022-05-12 01:18 UTC, FlaviaCohen requested changes

2022-05-12 01:18 UTC, FlaviaCohen commented on src/Services/privateApiService.js
> +    return axios.put(`${process.env.REACT_APP_URL_BASE_ENDPOINT}${process.env.REACT_APP_URL_MEMBER_PATH}/${id}`,body,config)
Podrias concatenarlo asi: 

`${process.env.REACT_APP_URL_BASE_ENDPOINT + process.env.REACT_APP_URL_MEMBER_PATH + '/' + id}`

2022-05-12 01:18 UTC, FlaviaCohen commented on src/Services/privateApiService.js
> +    return axios.put(`${process.env.REACT_APP_URL_BASE_ENDPOINT}${process.env.REACT_APP_URL_MEMBER_PATH}/${id}`,body,config)
Lo mismo para todos los otros endpoints

2022-05-12 14:12 UTC, agusconde18 commented on src/Services/privateApiService.js
> +    return axios.put(`${process.env.REACT_APP_URL_BASE_ENDPOINT}${process.env.REACT_APP_URL_MEMBER_PATH}/${id}`,body,config)
Realizado

2022-05-12 22:14 UTC, FlaviaCohen approved these changes

2022-05-12 22:14 UTC, merged