Feature/FS01-32 Register form
alkemyTech/BBVA-React-T1 pull request #9
Opened 2022-05-10 22:03 UTC by erikafarias

Layout de formulario para registro creado. Envía mensajes de error cuando no se cumplen las validaciones.
Se elimina la imagen en versión mobile.

2022-05-11 00:18 UTC, erikafarias commented
Comentario extra: en Jira agregué las vistas del componente. Si es necesario (o para tener en cuenta en próximos PR) los adjunto acá también.

2022-05-11 02:18 UTC, FlaviaCohen requested changes

2022-05-11 02:18 UTC, FlaviaCohen commented on src/Components/Auth/RegisterForm.js
> +    if (e.target.name === "name") {
Hay una forma mas resumida de hacer este handleChange: 

```
const handleChange = (e) => {
    setInitialValues({...initialValues, [e.target.name]: e.target.value})
} 
```

2022-05-11 02:18 UTC, FlaviaCohen commented on src/Components/Auth/RegisterForm.js
> +    if (
Esta logica deberia estar dentro de una funcion handleError. No es una buena practica declarar logica directamente dentro de un useEffect sino que la declaramos en una funcion aparte y dentro del useEffect solo la ejecutamos.

2022-05-11 02:18 UTC, FlaviaCohen commented on src/Components/Auth/RegisterForm.js
> +    if (
Mismo comentario que el anterior

2022-05-11 02:18 UTC, FlaviaCohen commented on src/Components/Auth/RegisterForm.js
> +    console.log(initialValues);
No dejamos console.logs en los PRs

2022-05-11 02:18 UTC, FlaviaCohen commented on src/Components/FormStyles.css
> +.form-container, form{
No es una buena practica declarar estilos directamente a tags ya que puede llevar a colisiones. 
Si vas a estilar el form hay que darle una clase.

2022-05-11 02:18 UTC, FlaviaCohen commented on src/Components/FormStyles.css
> +    background-color: #ff0000 !important;
Si estas teniendo que usar important aca es porque hay una colision de estilos. important es casi una mala palabra en cuanto a practicas de css.

2022-05-11 02:18 UTC, FlaviaCohen commented on src/Components/FormStyles.css
> +.img-form img {
Mismo comentario que en form

2022-05-11 02:18 UTC, FlaviaCohen commented on src/Components/FormStyles.css
> +@media (max-width: 600px) {
La forma correcta de declarar una media query es dentro de la clase correspondiente. Si declaramos una media query y dentro las clases vamos a terminar con clases repetidas y el estilo disperso en varios lugares. 

Es preferible repetir varias veces la misma media query en diferentes clases y que el estilo de una misma clase quede en el mismo lugar. Esto hace mas facil mantener codigo de proyectos grandes.

2022-05-11 14:07 UTC, FlaviaCohen requested changes

2022-05-11 14:07 UTC, FlaviaCohen commented on src/Components/Auth/RegisterForm.js
> +  useEffect(() => {
Creo que no es necesario tener dos useEffect escuchando dos valores diferentes y dos handlers de error. Si pones toda la logica en una misma funcion y haces que el useEffect escuche ambos valores va a funcionar ya que va a entrar en los if que sea necesario y en los otros no cuando corresponda.

2022-05-11 14:07 UTC, FlaviaCohen commented on src/Components/Auth/RegisterForm.js
> +    return initialValues;
Para que estas retornando initialValues aca?

2022-05-11 14:07 UTC, FlaviaCohen commented on src/Components/Auth/RegisterForm.js
> +            style={{ backgroundColor: "#ff0000" }}
Los estilos inline son una mala practica. Este estilo deberia ir en la hoja de estilo. Si esta colisionando es porque se debe estar pisando con otro.  Inspecciona el elemento en la consola del navegador y fijate que es lo que lo esta pisando.

2022-05-11 14:11 UTC, erikafarias commented on src/Components/Auth/RegisterForm.js
> +  useEffect(() => {
Intenté hacerlo de esa forma pero no funcionaba, entraba en uno de los métodos y en el otro no. Mismo intentando hacerlo en el mismo handleError por eso opté por separarlos

2022-05-11 14:12 UTC, erikafarias commented on src/Components/Auth/RegisterForm.js
> +    return initialValues;
Porque me pide guardar un objeto con los campos completados, pero no estaba segura si era necesario retornarlo o no

2022-05-12 01:28 UTC, FlaviaCohen requested changes

2022-05-12 01:28 UTC, FlaviaCohen commented on src/Components/Auth/RegisterForm.js
>      localStorage.setItem("token", "tokenValueExample");
Aca hay que enviar al endpoint de register la informacion del formulario de registro (name, email y password), eso te va a devolver un token y ese es el token que tenes que setear en el localStorage. Sino el formulario nunca va a funcionar de verdad.

2022-05-12 01:28 UTC, FlaviaCohen commented on src/Components/Auth/RegisterForm.js
> +    setError({
Esta logica declarala en un handleError por fuera del useEffect y dentro solo ejecutala

2022-05-12 01:29 UTC, FlaviaCohen commented
Resolver conflictos

2022-05-12 21:46 UTC, erikafarias commented
Hoy estuvimos con Jenko y Agus tratando de ver cómo hacer para que el método post funcione y la única solución que encontramos fue agregarle los .toString al body que se envía en la petición. Quizás hay alguna mejor forma, o hay algo que no estamos viendo pero fue lo único que sirvió

2022-05-12 22:49 UTC, FlaviaCohen commented on src/Components/Auth/RegisterForm.js
>      localStorage.setItem("token", "tokenValueExample");
Si, hoy lo explique en la daily. Las tarjetas son de aceleraciones anteriores mas largas y estan pensadas para tener mucho mas que dos sprints. Por eso en esta tenemos que resolver ya la llamada a la api para el registro

2022-05-12 22:50 UTC, FlaviaCohen commented
Usar el metodo .toString() esta perfecto si la api esta esperando strings

2022-05-12 22:54 UTC, FlaviaCohen requested changes

2022-05-12 22:54 UTC, FlaviaCohen commented on src/Components/Auth/RegisterForm.js
> +  const { name, lastName, email, password, confirmPassword } = initialValues;
Esta desestructuracion debe ir dentro del handleSubmit

2022-05-12 22:55 UTC, FlaviaCohen commented
Recorda adjuntar capturas de pantalla en el PR

2022-05-12 23:03 UTC, erikafarias commented on src/Components/Auth/RegisterForm.js
> +  const { name, lastName, email, password, confirmPassword } = initialValues;
Aunque lo utilice en otros lugares?

2022-05-12 23:07 UTC, erikafarias commented
Perdón, las había adjuntado en Jira.
Vista de los campos, todos ellos **required**
![image-20220510-233512](https://user-images.githubusercontent.com/82243624/168181296-37a85f4a-380e-4518-b67d-67c345498583.png)
Vista de los mensajes de error  al no cumplir la validación
![image-20220510-202705](https://user-images.githubusercontent.com/82243624/168181299-fe868a7f-794a-42be-822e-ae2cc5c9f6a1.png)
Vista al pasar validaciones
![image-20220510-202757](https://user-images.githubusercontent.com/82243624/168181303-2e65e50d-6eba-41b4-a293-399ff9564471.png)

2022-05-12 23:21 UTC, erikafarias commented
> Perdón, las había adjuntado en Jira. Vista de los campos, todos ellos **required** ![image-20220510-233512](https://user-images.githubusercontent.com/82243624/168181296-37a85f4a-380e-4518-b67d-67c345498583.png) Vista de los mensajes de error al no cumplir la validación ![image-20220510-202705](https://user-images.githubusercontent.com/82243624/168181299-fe868a7f-794a-42be-822e-ae2cc5c9f6a1.png) Vista al pasar validaciones ![image-20220510-202757](https://user-images.githubusercontent.com/82243624/168181303-2e65e50d-6eba-41b4-a293-399ff9564471.png)

Luego de eso le agregue el mensaje de "¿Ya tienes una cuenta? Iniciar sesión" pero lo demás sigue igual

2022-05-13 00:00 UTC, FlaviaCohen requested changes

2022-05-13 00:00 UTC, FlaviaCohen commented on src/Components/Auth/RegisterForm.js
> +  const { name, lastName, email, password, confirmPassword } = initialValues;
ah no... no habia visto que lo usabas en dos metodos

2022-05-13 00:00 UTC, FlaviaCohen commented on src/Components/Auth/RegisterForm.js
> +    setError({
falto esto

2022-05-13 00:00 UTC, FlaviaCohen commented
Solucionar conflictos

2022-05-13 14:30 UTC, FlaviaCohen requested changes

2022-05-13 14:30 UTC, FlaviaCohen commented on src/App.js
> +          <Route path="/Nosotros" component={Nosotros} />
Este cambio es correcto?

2022-05-13 14:30 UTC, FlaviaCohen commented
Solucionar conflictos

2022-05-13 14:34 UTC, erikafarias commented on src/App.js
> +          <Route path="/Nosotros" component={Nosotros} />
Solucionado en el merge

2022-05-14 13:27 UTC, FlaviaCohen approved these changes

2022-05-14 13:28 UTC, merged